# Generated by Django 3.2.7 on 2021-09-08 03:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='blog',
            name='body',
            field=models.CharField(default='test', max_length=100),
            preserve_default=False,
        ),
    ]
